[package]
name = "server_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.17"
tokio = { version = "1.28.0", features = ["full"] }
webbrowser = "0.8.9"
